### ISSUE TITLE
Mobile CI/CD with Bitrise (Manual)

### ISSUE THREAD

**Issue by igorlamos** [beplus-bootstrap/mobile#19]
Using [Bitrise](https://bitrise.io) as a Mobile CI\/CD Provider → Configuring manually\.

**Comment by igorlamos** [comment]
Link to feature: https://beplus.productboard.com/feature-board/planning/features/27859949

**Comment by igorlamos** [comment]
https://docs.be.plus/training/playbooks/mobile/cicd/bitrise

**Comment by Pictureitgold** [comment]
Why would I get flag on a developer app. Chill
